[package]
name = "zed_zig"
version = "0.3.5"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/zig.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }
zed_extension_api = "0.7.0"
