[package]
name = "zed_zig"
version = "0.3.4"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/zig.rs"
crate-type = ["cdylib"]

[dependencies]
urlencoding = "2.1.3"
zed_extension_api = "0.3.0"
serde = { version = "1.0.219", features = ["derive"] }
