id = "zig"
name = "Zig"
description = "Zig support."
version = "0.3.5"
schema_version = 1
authors = ["Allan Calix <contact@acx.dev>"]
repository = "https://github.com/zed-extensions/zig"

[language_servers.zls]
name = "zls"
language = "Zig"

[grammars.zig]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-zig"
commit = "6479aa13f32f701c383083d8b28360ebd682fb7d"

[debug_locators.zig-locator]
