id = "zig"
name = "Zig"
description = "Zig support."
version = "0.3.4"
schema_version = 1
authors = ["Allan Calix <contact@acx.dev>"]
repository = "https://github.com/zed-extensions/zig"

[language_servers.zls]
name = "zls"
language = "Zig"

[grammars.zig]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-zig"
commit = "eb7d58c2dc4fbeea4745019dee8df013034ae66b"

[[capabilities]]
kind = "process:exec"
command = "zig"
args = ["version"]
